name: Build_Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get ./src
      - name: Build
        run: go build -C ./src
      - name: Test with the Go CLI
        run: go test ./test
