name: Build_Test_Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build_test_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Auto Changelog
        uses: ardalanamini/auto-changelog@v4.0.1
        id  : changelog
        with:
          github-token            : ${{ secrets.GITHUB_TOKEN }}
          commit-types            : |
            feat: New Features
            fix: Bug Fixes
            build: Build System & Dependencies
            perf: Performance Improvements
            docs: Documentation
            test: Tests
            refactor: Refactors
            chore: Chores
            ci: CI
            cd: CD
            style: Code Style
            revert: Reverts
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - run: go get dagger.io/dagger@latest
      - run: go run ci/build_test_release.go
      - name: publish project
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          #linux build
          release_name_linux="Tech_Radar-$tag-linux"
          tar -C ./dist -czvf "${release_name_linux}.tar.gz" Tech_Radar-linux

          #windows build
          release_name_win="Tech_Radar-$tag-win"
          tar -C ./dist -czvf "${release_name_win}.tar.gz" Tech_Radar-windows

          #mac build
          release_name_mac="Tech_Radar-$tag-mac"
          tar -C ./dist -czvf "${release_name_mac}.tar.gz" Tech_Radar-darwin
          
      - name: Release project
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.changelog.outputs.changelog}}
          files: "*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            